"""Planted-symmetry generator: build a task with a chosen shortcut set.

The algebraic family gives closed forms but only reaches a few values of ``|RS|``
with a rigid structure (cyclic shifts). To study the ``|RS|`` -> grounding
relationship across many tasks we need direct control of the shortcut set,
including *non-injective* shortcuts (concept collapses), which the modular family
never produces.

Construction: pick a set of maps ``G``, quotient the concept grid by the
equivalence "reachable from each other under ``G``", and give each orbit a random
label. Any ``alpha in G`` then preserves labels by construction, so ``RS ⊇ G``.

Two honest details:

- ``RS`` can come out **strictly larger** than ``G`` (the random labelling may
  accidentally identify more). Such samples are **kept and recorded**, never
  rejected -- rejection sampling would silently bias the task distribution toward
  whatever is easy to plant, which is exactly the kind of quiet selection effect
  that invalidates a correlational study.
- The oracle is run on every generated task, so the recorded ``|RS|`` is always
  measured rather than assumed.
"""

from __future__ import annotations

import itertools

import numpy as np

from ..concepts import ConceptSpace
from ..tasks import Task


def cyclic_group(k: int, step: int) -> list[np.ndarray]:
    """Maps generated by ``x -> x + step (mod k)``."""
    out, cur = [], np.arange(k)
    for _ in range(k):
        out.append(cur.copy())
        cur = (cur + step) % k
        if np.array_equal(cur, np.arange(k)):
            break
    out.append(np.arange(k))
    uniq = {m.tobytes(): m for m in out}
    return list(uniq.values())


def collapse_map(k: int, merge: list[tuple[int, int]]) -> np.ndarray:
    """A non-injective map merging the given concept pairs."""
    alpha = np.arange(k)
    for a, b in merge:
        alpha[a] = b
    return alpha


def _orbit_labels(k: int, n: int, maps: list[np.ndarray], rng: np.random.Generator):
    """Assign each orbit of the grid under ``maps`` a distinct random label."""
    grid = list(itertools.product(range(k), repeat=n))
    index = {c: i for i, c in enumerate(grid)}
    parent = list(range(len(grid)))

    def find(a: int) -> int:
        while parent[a] != a:
            parent[a] = parent[parent[a]]
            a = parent[a]
        return a

    def union(a: int, b: int) -> None:
        ra, rb = find(a), find(b)
        if ra != rb:
            parent[max(ra, rb)] = min(ra, rb)

    for c in grid:
        for m in maps:
            union(index[c], index[tuple(int(m[v]) for v in c)])

    roots = sorted({find(i) for i in range(len(grid))})
    remap = {r: i for i, r in enumerate(roots)}
    labels = np.array([remap[find(i)] for i in range(len(grid))], dtype=np.int64)
    # Shuffle label identities so the label alphabet carries no ordinal signal.
    perm = rng.permutation(len(roots))
    return perm[labels], len(roots)


def planted_task(
    k: int,
    n: int,
    maps: list[np.ndarray],
    rng: np.random.Generator,
    name: str | None = None,
) -> Task:
    """A task whose shortcut set provably contains ``maps``."""
    labels, n_labels = _orbit_labels(k, n, maps, rng)
    return Task(
        name=name or f"planted_k{k}_n{n}_g{len(maps)}",
        space=ConceptSpace(k=k, n_slots=n),
        label_table=labels.reshape((k,) * n).astype(np.int16),
        support=np.array(list(itertools.product(range(k), repeat=n)), dtype=np.int16),
        n_labels=n_labels,
        meta={"generator": "planted", "planted_size": len(maps)},
    )


def random_planted(
    k: int, n: int, rng: np.random.Generator, kind: str | None = None
) -> tuple[Task, int]:
    """Sample a planted task with a randomly chosen symmetry. Returns ``(task, |G|)``."""
    kind = kind or rng.choice(["identity", "cyclic", "collapse", "mixed"])
    if kind == "identity":
        maps = [np.arange(k)]
    elif kind == "cyclic":
        step = int(rng.integers(1, k))
        maps = cyclic_group(k, step)
    elif kind == "collapse":
        n_merge = int(rng.integers(1, max(2, k // 2)))
        pairs = [
            (int(a), int(b)) for a, b in rng.choice(k, size=(n_merge, 2), replace=True) if a != b
        ]
        maps = [np.arange(k), collapse_map(k, pairs)] if pairs else [np.arange(k)]
    else:
        step = int(rng.integers(1, k))
        maps = cyclic_group(k, step)
        a, b = rng.choice(k, size=2, replace=False)
        maps = [*maps, collapse_map(k, [(int(a), int(b))])]
    return planted_task(k, n, maps, rng), len(maps)
